#!/bin/sh

ART="/tmp/.music_cover"

is_playing() {
    status=`playerctl --player=spotify status`

    if [[ "$status" == "Playing" ]]; then
        echo 1
    else
        echo 0
    fi
}

get_song() {
    song=`playerctl --player=spotify metadata --format {{title}}`
    echo $song
}

get_artist() {
    artist=`playerctl --player=spotify metadata --format {{artist}}`
    echo $artist
}

get_album() {
    album=`playerctl --player=spotify metadata --format {{album}}`
    echo $album
}

get_duration() {
    status="$(is_playing)"

    if [[ "$status" == 1 ]]; then
        duration=`playerctl --player=spotify metadata | grep length | awk '{print $3 / 1000000}'`
        echo $duration
    fi
}

get_position() {
    status="$(is_playing)"

    if [[ "$status" == 1 ]]; then
        position=`playerctl --player=spotify position`
        echo $position
    fi
}

get_position_percentage() {
    status="$(is_playing)"

    if [[ "$status" == 1 ]]; then
        duration="$(get_duration)"
        position="$(get_position)"

        echo $position $duration | awk '{print ($1 / $2) * 100 }'
    fi
}

get_cover() {
    status="$(is_playing)"

    if [[ "$status" == 1 ]]; then
        art_url=`playerctl --player=spotify metadata | grep artUrl | awk '{print $3}'`
        wget $art_url -O $ART &> /dev/null
        echo "$ART"
    fi
}

toggle_music() {
    playerctl --player=spotify play-pause
}

next_music() {
    playerctl --player=spotify next
    get_cover
}

previous_music() {
    playerctl --player=spotify previous
    get_cover
}

if [[ "$1" == "--playing" ]]; then
    is_playing
elif [[ "$1" == "--song" ]]; then
    get_song
elif [[ "$1" == "--artist" ]]; then
    get_artist
elif [[ "$1" == "--album" ]]; then
    get_album
elif [[ "$1" == "--duration" ]]; then
    get_duration
elif [[ "$1" == "--position" ]]; then
    get_position
elif [[ "$1" == "--pospercentage" ]]; then
    get_position_percentage
elif [[ "$1" == "--cover" ]]; then
    get_cover
elif [[ "$1" == "--toggle" ]]; then
    toggle_music
elif [[ "$1" == "--next" ]]; then
    next_music
elif [[ "$1" == "--previous" ]]; then
    previous_music
elif [[ "$1" == "--setposition" ]]; then
    duration="$(get_duration)"
    pos_in_secs=`echo $duration $2 | awk '{print $1 * ($2 / 100)}'`

    playerctl --player=spotify position $pos_in_secs
else
    get_song
fi
